# Generated by Django 5.1.5 on 2025-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='name',
            field=models.CharField(default='Nombre por defecto', max_length=255, unique=True),
        ),
    ]
